// ============================================================
//  喝水小助手 - 皮肤动画清单
//  共 128 个动画 | 按需加载
//  数据路径: skins/{稀有度}/{文件名}.json
// ============================================================

const SKIN_DATA = {
  '咖啡杯图标': {name:'咖啡杯图标',icon:'☕',desc:'',rarity:'common',file:'☕咖啡杯图标.json'},
  '星巴克': {name:'星巴克',icon:'☕',desc:'',rarity:'common',file:'☕星巴克.json'},
  '皮卡丘': {name:'皮卡丘',icon:'⚡',desc:'',rarity:'common',file:'⚡皮卡丘.json'},
  '拽铅笔': {name:'拽铅笔',icon:'✏',desc:'',rarity:'common',file:'✏️拽铅笔.json'},
  '❤️恋爱心': {name:'❤️恋爱心',icon:'',desc:'',rarity:'common',file:'❤️恋爱心.json'},
  '双层牛肉汉堡': {name:'双层牛肉汉堡',icon:'🎨',desc:'',rarity:'common',file:'双层牛肉汉堡.json'},
  '开心杯': {name:'开心杯',icon:'🎨',desc:'',rarity:'common',file:'开心杯.json'},
  '牛油果': {name:'牛油果',icon:'🎨',desc:'',rarity:'common',file:'牛油果.json'},
  '狂奔骆驼': {name:'狂奔骆驼',icon:'🎨',desc:'',rarity:'common',file:'狂奔骆驼.json'},
  '滑板球': {name:'滑板球',icon:'🍊',desc:'',rarity:'common',file:'🍊滑板球.json'},
  '行走橙子': {name:'行走橙子',icon:'🍊',desc:'',rarity:'common',file:'🍊行走橙子.json'},
  '醉瓶': {name:'醉瓶',icon:'🍺',desc:'',rarity:'common',file:'🍺醉瓶.json'},
  '🐑箭头羊': {name:'🐑箭头羊',icon:'',desc:'',rarity:'common',file:'🐑箭头羊.json'},
  '🐰傻蛋兔子': {name:'🐰傻蛋兔子',icon:'',desc:'',rarity:'common',file:'🐰傻蛋兔子.json'},
  '🐰睡觉兔子': {name:'🐰睡觉兔子',icon:'',desc:'',rarity:'common',file:'🐰睡觉兔子.json'},
  '🐱毛线猫': {name:'🐱毛线猫',icon:'',desc:'',rarity:'common',file:'🐱毛线猫.json'},
  '小白': {name:'小白',icon:'🐶',desc:'',rarity:'common',file:'🐶小白.json'},
  '青蛙抓虫': {name:'青蛙抓虫',icon:'🐸',desc:'',rarity:'common',file:'🐸青蛙抓虫.json'},
  '可爱小白': {name:'可爱小白',icon:'🐾',desc:'',rarity:'common',file:'🐾可爱小白.json'},
  '小轿车': {name:'小轿车',icon:'📄',desc:'',rarity:'common',file:'小轿车.json'},
  '⌨️敲击键盘': {name:'⌨️敲击键盘',icon:'',desc:'',rarity:'rare',file:'⌨️敲击键盘.json'},
  '☕紫色保温杯': {name:'☕紫色保温杯',icon:'',desc:'',rarity:'rare',file:'☕紫色保温杯.json'},
  '⚡闪电皮卡丘': {name:'⚡闪电皮卡丘',icon:'',desc:'',rarity:'rare',file:'⚡闪电皮卡丘.json'},
  '山路汽车': {name:'山路汽车',icon:'⛰',desc:'',rarity:'rare',file:'⛰️山路汽车.json'},
  '钱来': {name:'钱来',icon:'🎨',desc:'',rarity:'rare',file:'钱来.json'},
  '猫猫卖萌': {name:'猫猫卖萌',icon:'🎨',desc:'',rarity:'rare',file:'猫猫卖萌.json'},
  '大蒜癞蛤蟆': {name:'大蒜癞蛤蟆',icon:'🎨',desc:'',rarity:'rare',file:'大蒜癞蛤蟆.json'},
  '香肠狗': {name:'香肠狗',icon:'🎨',desc:'',rarity:'rare',file:'香肠狗.json'},
  '🌈好运彩虹花': {name:'🌈好运彩虹花',icon:'',desc:'',rarity:'rare',file:'🌈好运彩虹花.json'},
  '🐌粉色蜗牛': {name:'🐌粉色蜗牛',icon:'',desc:'',rarity:'rare',file:'🐌粉色蜗牛.json'},
  '🐌蹦迪蜗牛': {name:'🐌蹦迪蜗牛',icon:'',desc:'',rarity:'rare',file:'🐌蹦迪蜗牛.json'},
  '蛇皮走位': {name:'蛇皮走位',icon:'🐍',desc:'',rarity:'rare',file:'🐍蛇皮走位.json'},
  '🐕狗子墩墩': {name:'🐕狗子墩墩',icon:'',desc:'',rarity:'rare',file:'🐕狗子墩墩.json'},
  '算命兔': {name:'算命兔',icon:'🐰',desc:'',rarity:'rare',file:'算命兔.json'},
  '🐱傻猫': {name:'🐱傻猫',icon:'',desc:'',rarity:'rare',file:'🐱傻猫.json'},
  '🐶小短腿': {name:'🐶小短腿',icon:'',desc:'',rarity:'rare',file:'🐶小短腿.json'},
  '👁️黄色痞老板': {name:'👁️黄色痞老板',icon:'',desc:'',rarity:'rare',file:'👁️黄色痞老板.json'},
  '拽拽的警长': {name:'拽拽的警长',icon:'👮',desc:'',rarity:'rare',file:'👮拽拽的警长.json'},
  '生气痞老板': {name:'生气痞老板',icon:'👽',desc:'',rarity:'rare',file:'生气痞老板.json'},
  '开箱钻戒': {name:'开箱钻戒',icon:'💍',desc:'',rarity:'rare',file:'💍开箱钻戒.json'},
  '炸弹人': {name:'炸弹人',icon:'💣',desc:'',rarity:'rare',file:'💣炸弹人.json'},
  '📖读书杯子': {name:'📖读书杯子',icon:'',desc:'',rarity:'rare',file:'📖读书杯子.json'},
  '火': {name:'火',icon:'🔥',desc:'',rarity:'rare',file:'🔥火.json'},
  '😴睡觉杯': {name:'😴睡觉杯',icon:'',desc:'',rarity:'rare',file:'😴睡觉杯.json'},
  '太空人': {name:'太空人',icon:'🚀',desc:'',rarity:'rare',file:'🚀太空人.json'},
  '太空旅行': {name:'太空旅行',icon:'🚀',desc:'',rarity:'rare',file:'🚀太空旅行.json'},
  '🚲骑车杯子': {name:'🚲骑车杯子',icon:'',desc:'',rarity:'rare',file:'🚲骑车杯子.json'},
  '外星人': {name:'外星人',icon:'🛸',desc:'',rarity:'rare',file:'🛸外星人.json'},
  '外星飞船': {name:'外星飞船',icon:'🛸',desc:'',rarity:'rare',file:'🛸外星飞船.json'},
  '灰狗': {name:'灰狗',icon:'🥋',desc:'',rarity:'rare',file:'🥋灰狗.json'},
  '丑驯鹿': {name:'丑驯鹿',icon:'🦌',desc:'',rarity:'rare',file:'🦌丑驯鹿.json'},
  '圣诞鹅送礼': {name:'圣诞鹅送礼',icon:'🦢',desc:'',rarity:'rare',file:'🦢圣诞鹅送礼.json'},
  '火烈鸟': {name:'火烈鸟',icon:'🦩',desc:'',rarity:'rare',file:'🦩火烈鸟.json'},
  '瑜伽': {name:'瑜伽',icon:'🧘',desc:'',rarity:'rare',file:'🧘瑜伽.json'},
  '茶壶茶杯': {name:'茶壶茶杯',icon:'🫖',desc:'',rarity:'rare',file:'茶壶茶杯.json'},
  '雪人': {name:'雪人',icon:'⛄',desc:'',rarity:'epic',file:'⛄雪人.json'},
  '汽车旅游': {name:'汽车旅游',icon:'✈',desc:'',rarity:'epic',file:'✈️汽车旅游.json'},
  '狗子坐火箭': {name:'狗子坐火箭',icon:'🎨',desc:'',rarity:'epic',file:'狗子坐火箭.json'},
  '猫猫社会摇': {name:'猫猫社会摇',icon:'🎨',desc:'',rarity:'epic',file:'猫猫社会摇.json'},
  '野人': {name:'野人',icon:'🎨',desc:'',rarity:'epic',file:'野人.json'},
  '彩虹猫': {name:'彩虹猫',icon:'🌈',desc:'',rarity:'epic',file:'🌈彩虹猫.json'},
  '🌱运气王小花': {name:'🌱运气王小花',icon:'',desc:'',rarity:'epic',file:'🌱运气王小花.json'},
  '南瓜怪人': {name:'南瓜怪人',icon:'🎃',desc:'',rarity:'epic',file:'🎃南瓜怪人.json'},
  '女巫': {name:'女巫',icon:'🎃',desc:'',rarity:'epic',file:'🎃女巫.json'},
  '🎭小蓝': {name:'🎭小蓝',icon:'',desc:'',rarity:'epic',file:'🎭小蓝.json'},
  '🎭打工地地': {name:'🎭打工地地',icon:'',desc:'',rarity:'epic',file:'🎭打工地地.json'},
  '🎭兼职球球': {name:'🎭兼职球球',icon:'',desc:'',rarity:'epic',file:'🎭兼职球球.json'},
  '三人行': {name:'三人行',icon:'🎮',desc:'',rarity:'epic',file:'🎮三人行.json'},
  '骰子': {name:'骰子',icon:'🎲',desc:'',rarity:'epic',file:'🎲骰子.json'},
  '🐱小灰': {name:'🐱小灰',icon:'',desc:'',rarity:'epic',file:'🐱小灰.json'},
  '🐱小蓝': {name:'🐱小蓝',icon:'',desc:'',rarity:'epic',file:'🐱小蓝.json'},
  '🐱猫猫王': {name:'🐱猫猫王',icon:'',desc:'',rarity:'epic',file:'🐱猫猫王.json'},
  '🐱运营猫': {name:'🐱运营猫',icon:'',desc:'',rarity:'epic',file:'🐱运营猫.json'},
  '🐶气球小狗': {name:'🐶气球小狗',icon:'',desc:'',rarity:'epic',file:'🐶气球小狗.json'},
  '💰钱飞来': {name:'💰钱飞来',icon:'',desc:'',rarity:'epic',file:'💰钱飞来.json'},
  '薛定谔猫': {name:'薛定谔猫',icon:'📦',desc:'',rarity:'epic',file:'📦薛定谔猫.json'},
  '😎死渣男': {name:'😎死渣男',icon:'',desc:'',rarity:'epic',file:'😎死渣男.json'},
  '二逼游戏机': {name:'二逼游戏机',icon:'😏',desc:'',rarity:'epic',file:'😏二逼游戏机.json'},
  '😴睡觉小幽灵': {name:'😴睡觉小幽灵',icon:'',desc:'',rarity:'epic',file:'😴睡觉小幽灵.json'},
  '😻恋爱猫': {name:'😻恋爱猫',icon:'',desc:'',rarity:'epic',file:'😻恋爱猫.json'},
  '口水猫': {name:'口水猫',icon:'😿',desc:'',rarity:'epic',file:'口水猫.json'},
  '公交车': {name:'公交车',icon:'🚌',desc:'',rarity:'epic',file:'🚌公交车.json'},
  '房车': {name:'房车',icon:'🚐',desc:'',rarity:'epic',file:'🚐房车.json'},
  '越野车': {name:'越野车',icon:'🛞',desc:'',rarity:'epic',file:'越野车.json'},
  '阳澄湖大螃蟹': {name:'阳澄湖大螃蟹',icon:'🦀',desc:'',rarity:'epic',file:'🦀阳澄湖大螃蟹.json'},
  '☕复古咖啡磨': {name:'☕复古咖啡磨',icon:'',desc:'',rarity:'legendary',file:'☕复古咖啡磨.json'},
  '☕复古咖啡袋': {name:'☕复古咖啡袋',icon:'',desc:'',rarity:'legendary',file:'☕复古咖啡袋.json'},
  '☕泡澡男孩': {name:'☕泡澡男孩',icon:'',desc:'',rarity:'legendary',file:'☕泡澡男孩.json'},
  '坟头蹦迪仔': {name:'坟头蹦迪仔',icon:'',desc:'',rarity:'legendary',file:'坟头蹦迪仔.json'},
  '摇滚瓶子': {name:'摇滚瓶子',icon:'',desc:'',rarity:'legendary',file:'摇滚瓶子.json'},
  '樱落无辞': {name:'樱落无辞',icon:'',desc:'',rarity:'legendary',file:'樱落无辞.json'},
  '🌈暴走小黑喵': {name:'🌈暴走小黑喵',icon:'',desc:'',rarity:'legendary',file:'🌈暴走小黑喵.json'},
  '🌙开斋节清真寺': {name:'🌙开斋节清真寺',icon:'',desc:'',rarity:'legendary',file:'🌙开斋节清真寺.json'},
  '🌙斋月': {name:'🌙斋月',icon:'',desc:'',rarity:'legendary',file:'🌙斋月.json'},
  '🌸花枝蝶树': {name:'🌸花枝蝶树',icon:'',desc:'',rarity:'legendary',file:'🌸花枝蝶树.json'},
  '🌿比耶快乐草': {name:'🌿比耶快乐草',icon:'',desc:'',rarity:'legendary',file:'🌿比耶快乐草.json'},
  '🎄圣诞摆烂松': {name:'🎄圣诞摆烂松',icon:'',desc:'',rarity:'legendary',file:'🎄圣诞摆烂松.json'},
  '🎉街头酷妹': {name:'🎉街头酷妹',icon:'',desc:'',rarity:'legendary',file:'🎉街头酷妹.json'},
  '🎨扫帚通勤人': {name:'🎨扫帚通勤人',icon:'',desc:'',rarity:'legendary',file:'🎨扫帚通勤人.json'},
  '🎭球球玩球': {name:'🎭球球玩球',icon:'',desc:'',rarity:'legendary',file:'🎭球球玩球.json'},
  '🏖️椰树摸鱼选手': {name:'🏖️椰树摸鱼选手',icon:'',desc:'',rarity:'legendary',file:'🏖️椰树摸鱼选手.json'},
  '🐟浮光游鱼': {name:'🐟浮光游鱼',icon:'',desc:'',rarity:'legendary',file:'🐟浮光游鱼.json'},
  '🐱月上摸鱼喵': {name:'🐱月上摸鱼喵',icon:'',desc:'',rarity:'legendary',file:'🐱月上摸鱼喵.json'},
  '🐶云间小白': {name:'🐶云间小白',icon:'',desc:'',rarity:'legendary',file:'🐶云间小白.json'},
  '🐶度假摆烂基': {name:'🐶度假摆烂基',icon:'',desc:'',rarity:'legendary',file:'🐶度假摆烂基.json'},
  '🐶快乐舔狗': {name:'🐶快乐舔狗',icon:'',desc:'',rarity:'legendary',file:'🐶快乐舔狗.json'},
  '🐻吨吨奶茶狂魔': {name:'🐻吨吨奶茶狂魔',icon:'',desc:'',rarity:'legendary',file:'🐻吨吨奶茶狂魔.json'},
  '🐻小低头网瘾熊': {name:'🐻小低头网瘾熊',icon:'',desc:'',rarity:'legendary',file:'🐻小低头网瘾熊.json'},
  '🐼熬夜上分国宝': {name:'🐼熬夜上分国宝',icon:'',desc:'',rarity:'legendary',file:'🐼熬夜上分国宝.json'},
  '👋工位电子搭子': {name:'👋工位电子搭子',icon:'',desc:'',rarity:'legendary',file:'👋工位电子搭子.json'},
  '👻纸箱搬运侠': {name:'👻纸箱搬运侠',icon:'',desc:'',rarity:'legendary',file:'👻纸箱搬运侠.json'},
  '💀阴间打工人': {name:'💀阴间打工人',icon:'',desc:'',rarity:'legendary',file:'💀阴间打工人.json'},
  '💼打逃离工位超人': {name:'💼打逃离工位超人',icon:'',desc:'',rarity:'legendary',file:'💼打逃离工位超人.json'},
  '📖云端卷王': {name:'📖云端卷王',icon:'',desc:'',rarity:'legendary',file:'📖云端卷王.json'},
  '🕹️低配屠龙少年': {name:'🕹️低配屠龙少年',icon:'',desc:'',rarity:'legendary',file:'🕹️低配屠龙少年.json'},
  '🚀星际出逃选手': {name:'🚀星际出逃选手',icon:'',desc:'',rarity:'legendary',file:'🚀星际出逃选手.json'},
  '🚗大奔': {name:'🚗大奔',icon:'',desc:'',rarity:'legendary',file:'🚗大奔.json'},
  '🚗大货车': {name:'🚗大货车',icon:'',desc:'',rarity:'legendary',file:'🚗大货车.json'},
  '🚗牛逼黄金车': {name:'🚗牛逼黄金车',icon:'',desc:'',rarity:'legendary',file:'🚗牛逼黄金车.json'},
  '🚗短途流浪小队': {name:'🚗短途流浪小队',icon:'',desc:'',rarity:'legendary',file:'🚗短途流浪小队.json'},
  '🛵追风干饭配送员': {name:'🛵追风干饭配送员',icon:'',desc:'',rarity:'legendary',file:'🛵追风干饭配送员.json'},
  '🤖人工智障打工机': {name:'🤖人工智障打工机',icon:'',desc:'',rarity:'legendary',file:'🤖人工智障打工机.json'},
  '🦋蝴蝶机器人之恋': {name:'🦋蝴蝶机器人之恋',icon:'',desc:'',rarity:'legendary',file:'🦋蝴蝶机器人之恋.json'},
  '🧛德古拉': {name:'🧛德古拉',icon:'',desc:'',rarity:'legendary',file:'🧛德古拉.json'},
  '🧟科学怪人': {name:'🧟科学怪人',icon:'',desc:'',rarity:'legendary',file:'🧟科学怪人.json'},
  '🧤骑士手套': {name:'🧤骑士手套',icon:'',desc:'',rarity:'legendary',file:'🧤骑士手套.json'},
  '🧪狗子键盘': {name:'🧪狗子键盘',icon:'',desc:'',rarity:'legendary',file:'🧪狗子键盘.json'},
  '彩纸': {name:'彩纸',icon:'🎊',desc:'',rarity:'other',file:'🎊彩纸.json'},
};

// 稀有度 → 文件夹名称映射
const RARITY_FOLDER = {
  'common':'普通',
  'rare':'稀有',
  'epic':'史诗',
  'legendary':'传说',
  'other':'其他',
};